/* piano.c */

/* System libraries */
#include <fcntl.h>
#include <linux/kd.h>

/* Include PHP API */
#include "php.h"

/* This module's header file */
#include "php_piano.h"

/* Define function entries */
zend_function_entry piano_functions[] = {
    PHP_FE(play_piano, NULL)
    { NULL, NULL, NULL }
};

zend_module_entry piano_module_entry = {
    STANDARD_MODULE_HEADER,
    PHP_PIANO_EXTNAME,
    piano_functions,        /* Function entries */
    PHP_MINIT(piano),       /* Module init */
    NULL,                   /* Module shutdown */
    NULL,                   /* Request init */
    NULL,                   /* Request shutdown */
    NULL,                   /* Module information */
    PHP_PIANO_VERSION,
    STANDARD_MODULE_PROPERTIES
};

/* Install module */
ZEND_GET_MODULE(piano)

/* Module init */
PHP_MINIT_FUNCTION(piano) {
    REGISTER_LONG_CONSTANT("PIANO_0",    1, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("PIANO_C",  261, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("PIANO_D",  293, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("PIANO_E",  329, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("PIANO_F",  349, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("PIANO_G",  392, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("PIANO_A",  440, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("PIANO_B",  493, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("PIANO_C6", 523, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("PIANO_D6", 587, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("PIANO_E6", 659, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("PIANO_F6", 698, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("PIANO_G6", 783, CONST_CS | CONST_PERSISTENT);

    return SUCCESS;
}

/* function play_piano(int $freq, int ms): void */
PHP_FUNCTION(play_piano) {
    int console_fd;
    int freq;
    int ms;

    if (zend_parse_parameters(ZEND_NUM_ARGS(), "ll", &freq, &ms) == FAILURE) {
        return;
    }

    if ((console_fd = open("/dev/console", O_WRONLY)) == -1) {
        fprintf(stderr, "Can't play the piano. Could not open /dev/console for writing.\n");
        exit(1);
    }

    /* the PC uses a base rate of 1,193,180 Hz, generated by an oscillator chip */
    ioctl(console_fd, KIOCSOUND, 1193180 / freq);
    /* beep for given duration */
    usleep(ms * 1000);

    /* KIOCSOUND generates an endless beep, we have to stop beeping */
    ioctl(console_fd, KIOCSOUND, 0);

    close(console_fd);
}
